trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Plan
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'
    - task: AzureCLI@2
      displayName: 'Init'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          
          terraform init \
            -backend-config="resource_group_name=ab-terrastorage" \
            -backend-config="storage_account_name=abstorageterra" \
            -backend-config="container_name=tf-state-container01" \
            -backend-config="key=$(backend-key)" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="use_oidc=true" \
            -backend-config="oidc_token=$idToken" \
            -backend-config="client_id=$servicePrincipalId" \
            -backend-config="tenant_id=$tenantId" \
            -backend-config="subscription_id=$(az account show --query id -o tsv)"
   
    # - task: TerraformTask@5
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'init'
    #     backendServiceArm: 'terra-con2'
    #     backendAzureRmStorageAccountName: 'abstorageterra'
    #     backendAzureRmContainerName: 'tf-state-container01'
    #     backendAzureRmKey: $(backend-key)
        

    # - task: TerraformTask@5
    #   displayName: 'Plan'
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'plan'
    #     environmentServiceNameAzureRM: 'terra-con'
    #     commandOptions: '-out=$(Build.ArtifactStagingDirectory)/tfplan'

    - task: AzureCLI@2
      displayName: 'Plan'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

          terraform plan -out=tfplan
          cp tfplan $(Build.ArtifactStagingDirectory)/tfplan 

    - publish: $(Build.ArtifactStagingDirectory)/tfplan
      artifact: tfplan
       

- stage: Apply
  dependsOn: Plan
  jobs:
  - job: Apply
    steps:
    - download: current
      artifact: tfplan

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'

    - task: AzureCLI@2
      displayName: 'Init'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          
          terraform init \
            -backend-config="resource_group_name=ab-terrastorage" \
            -backend-config="storage_account_name=abstorageterra" \
            -backend-config="container_name=tf-state-container01" \
            -backend-config="key=$(backend-key)" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="use_oidc=true" \
            -backend-config="oidc_token=$idToken" \
            -backend-config="client_id=$servicePrincipalId" \
            -backend-config="tenant_id=$tenantId" \
            -backend-config="subscription_id=$(az account show --query id -o tsv)"
         
    # - task: TerraformTask@5
    #   displayName: 'Apply'
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'apply'
    #     environmentServiceNameAzureRM: 'terra-con'
    #     commandOptions: '$(Pipeline.Workspace)/tfplan/tfplan'
 
    - task: AzureCLI@2
      displayName: 'Apply'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

          terraform apply $(Pipeline.Workspace)/tfplan/tfplan