trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Plan
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'

    - task: TerraformTaskV4@5
      displayName: 'Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'terra-con'
        backendAzureRmResourceGroupName: 'rg-linux-practice'
        backendAzureRmStorageAccountName: 'abstorage23'
        backendAzureRmContainerName: 'tf-state-container01'
        backendAzureRmKey: $(backend-key)
        backendAzureRmUseEntraIdForAuthentication: true

    - task: TerraformTaskV4@5
      displayName: 'Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'terra-con'
        commandOptions: '-out=$(Build.ArtifactStagingDirectory)/tfplan'

    - publish: $(Build.ArtifactStagingDirectory)/tfplan
      artifact: tfplan

- stage: Apply
  dependsOn: Plan
  jobs:
  - job: Apply
    steps:
    - download: current
      artifact: tfplan

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'

    - task: TerraformTaskV4@5
      displayName: 'Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'terra-con'
        backendAzureRmResourceGroupName: 'rg-linux-practice'
        backendAzureRmStorageAccountName: 'abstorage23'
        backendAzureRmContainerName: 'tf-state-container01'
        backendAzureRmKey: $(backend-key)
        backendAzureRmUseEntraIdForAuthentication: true

    - task: TerraformTaskV4@5
      displayName: 'Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'terra-con'
        commandOptions: '$(Pipeline.Workspace)/tfplan/tfplan'