trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Plan
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'
   
    - task: AzureCLI@2
      displayName: 'Init'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export  vARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

          echo "=== SERVICE CONNECTION IDENTITY ==="

          az ad sp show \
            --id $servicePrincipalId \
            --query "{name:displayName,clientId:appId,objectId:id}" \
            -o table

          echo "=== EFFECTIVE STORAGE RBAC ==="

          STORAGE_ID=$(az storage account show \
            --name abstorage23 \
            --resource-group storageacc \
            --query id -o tsv)

          az role assignment list \
            --assignee $servicePrincipalId \
            --scope "$STORAGE_ID" \
            --include-inherited \
            --query "[].{role:roleDefinitionName,scope:scope}" \
            -o table

          echo "=== BLOB TEST ==="

          az storage blob list \
            --account-name abstorage23 \
            --container-name state-files \
            --auth-mode login \
            -o table

          
          terraform init \
            -backend-config="resource_group_name=storageacc" \
            -backend-config="storage_account_name=abstorage23" \
            -backend-config="container_name=state-files" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="use_oidc=true" \
            -backend-config="oidc_token=$idToken" \
            -backend-config="client_id=$servicePrincipalId" \
            -backend-config="tenant_id=$tenantId" \
            -backend-config="subscription_id=$(az account show --query id -o tsv)"
   

    - task: AzureCLI@2
      displayName: 'Plan'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          terraform plan -out=tfplan
          cp tfplan $(Build.ArtifactStagingDirectory)/tfplan 
          
    - publish: $(Build.ArtifactStagingDirectory)/tfplan
      artifact: tfplan
    

- stage: Apply
  dependsOn: Plan
  jobs:
  - job: Apply
    steps:
    - download: current
      artifact: tfplan
    
      

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.10.5'

    - task: AzureCLI@2
      displayName: 'Init'
      inputs:
        azureSubscription: 'terra-con'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          
           terraform init \
            -backend-config="resource_group_name=storageacc" \
            -backend-config="storage_account_name=abstorage23" \
            -backend-config="container_name=state-files" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="use_oidc=true" \
            -backend-config="oidc_token=$idToken" \
            -backend-config="client_id=$servicePrincipalId" \
            -backend-config="tenant_id=$tenantId" \
            -backend-config="subscription_id=$(az account show --query id -o tsv)"



    # - task: TerraformTask@5
    #   displayName: 'Apply the infra'
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'apply'
    #     commandOptions: '$(Pipeline.Workspace)/tfplan/tfplan'
    #     environmentServiceNameAzureRM: 'terra-con'

    - task: AzureCLI@2
      displayName: Apply the infra
      inputs:
        azureSubscription: 'terra-con'
        scriptType: bash
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_USE_OIDC=true
          export ARM_OIDC_TOKEN=$idToken
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

          terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan 2>&1 | tee /tmp/tf.log || true
          echo "=== TERRAFORM DEBUG LOG (errors only) ==="
          grep -A 10 "error\|Error\|VMSS\|virtualMachine" /home/vsts/work/tf-debug.log | tail -100



    # - task: AzureCLI@2
    #   displayName: Apply the infra
    #   inputs:
    #     azureSubscription: 'terra-con'
    #     scriptType: bash
    #     scriptLocation: inlineScript
    #     addSpnToEnvironment: true
    #     inlineScript: |
    #       export ARM_USE_OIDC=true
    #       export ARM_OIDC_TOKEN=$idToken
    #       export ARM_CLIENT_ID=$servicePrincipalId
    #       export ARM_TENANT_ID=$tenantId
    #       export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

    #       terraform destroy -auto-approve